### PR TITLE
Rendering Bugfixes

### LINKED ISSUE #9: UI Improvements
## Features

- [x] Make the arrow keys advance all viewers along a given axis on keydown.

## Bugs

- [x] Aspect ratio of the 3D projection matrix is messed when you resize the screen.
- [x] Make it so that you can have 1-2 viewers active at the same time and it feels nice. (don't worry about 3+)

### PR DESCRIPTION
**Pull request by nicschumann**
Closes #9.

### Quality of Life Improvements:

- ~Make the margins overall smaller; make the margin between viewers consistent. (see attached screenshot for an example).~ _update: not gonna bother with this for now..._
- [x] Make the `Browser` sidebar collapsable.
- [x] Paste a comma-separated list of coordinates into a selector and have it fill out each input for you

Screenshot 2024-12-01 at 11 47 11 AM

### CODE REVIEW

**Comment by nicschumann** [comment]
I added "batched pasting": a functionality where if you paste in a comma-separated list of indices, ie:

```
421192, 0, 12600:12900, 5600:5900
```

It will populate the successive inputs with the comma-separated values. This makes it feel a lot nicer to get to the target slice.

Note that that the "batched paste" starts from the index of the input that you're currently focused in. If you put your cursor in the **second** input field, and paste the above string in, you will get a sequence of input fields populated with:

```
[5600:5900]  [421192]  [0]  [12600:12900]
```

So a typical paste will start from the **first** input field.

**Comment by nicschumann** [comment]
Demo of the multi-viewer functionality, rendering across arrays, tracking across an axis of both arrays using the `up`/`down` arrow keys, and a quality-of-life allowing you to paste in comma-separated lists of coordinates into the selector boxes, rather than needing to individually paste coords into each box separately.

https://github.com/user-attachments/assets/6f49dd3b-47b2-4424-ac9d-9a3eb7a27d6e

**Review by olimcc — APPROVED** [review]
looks great!

**Comment by nicschumann** [comment]
Adds collapsible sidebar.

Screenshot 2024-12-02 at 3 01 56 PM

**Pull request merged**
